const { prisma } = require('../config/db');
const { decrypt } = require('../utils/encryption');
const BrokerFactory = require('../integrations/brokers/broker.factory');

/**
 * Execute an Order Intent generated by Strategy Engine or User Action
 * @param {Object} params
 */
const executeOrder = async (params) => {
  const {
    userId,
    deploymentId,
    brokerAccountId,
    symbol,
    exchange = 'NSE',
    side,
    type = 'MARKET',
    quantity,
    price = 0.0,
    mode = 'PAPER',
    idempotencyKey,
  } = params;

  // 1. Check idempotency to prevent duplicate orders
  if (idempotencyKey) {
    const existingOrder = await prisma.order.findUnique({
      where: { idempotencyKey },
    });
    if (existingOrder) {
      return existingOrder;
    }
  }

  // 2. Paper Trading Execution
  if (mode === 'PAPER') {
    return await prisma.$transaction(async (tx) => {
      const fillPrice = price > 0 ? price : 2500.0; // Simulated fill price

      // Create Order
      const order = await tx.order.create({
        data: {
          deploymentId,
          userId,
          symbol,
          exchange,
          side,
          type,
          quantity,
          price: fillPrice,
          filledPrice: fillPrice,
          filledQuantity: quantity,
          status: 'FILLED',
          mode: 'PAPER',
          idempotencyKey,
        },
      });

      // Update or create Position
      const existingPosition = await tx.position.findFirst({
        where: { userId, deploymentId, symbol, status: 'OPEN' },
      });

      if (!existingPosition) {
        // Open new position
        const netQty = side === 'BUY' ? quantity : -quantity;
        await tx.position.create({
          data: {
            userId,
            deploymentId,
            symbol,
            exchange,
            quantity: netQty,
            avgPrice: fillPrice,
            ltp: fillPrice,
            status: 'OPEN',
          },
        });
      } else {
        // Update existing position
        const signedQty = side === 'BUY' ? quantity : -quantity;
        const newTotalQty = existingPosition.quantity + signedQty;

        if (newTotalQty === 0) {
          // Closed position: compute realized P&L
          const realizedPnl =
            side === 'SELL'
              ? (fillPrice - existingPosition.avgPrice) * quantity
              : (existingPosition.avgPrice - fillPrice) * quantity;

          await tx.position.update({
            where: { id: existingPosition.id },
            data: {
              quantity: 0,
              realizedPnl: existingPosition.realizedPnl + realizedPnl,
              unrealizedPnl: 0,
              status: 'CLOSED',
              ltp: fillPrice,
            },
          });
        } else {
          // Add to position or partial close
          await tx.position.update({
            where: { id: existingPosition.id },
            data: {
              quantity: newTotalQty,
              ltp: fillPrice,
            },
          });
        }
      }

      return order;
    });
  }

  // 3. Live Trading Execution via Broker Adapter
  const brokerAccount = await prisma.brokerAccount.findUnique({
    where: { id: brokerAccountId },
  });

  if (!brokerAccount || brokerAccount.status !== 'CONNECTED') {
    const error = new Error('Connected broker account required for LIVE trading');
    error.statusCode = 400;
    throw error;
  }

  const credentials = {
    accountRef: brokerAccount.accountRef,
    apiKey: decrypt(brokerAccount.apiKeyEncrypted),
    apiSecret: decrypt(brokerAccount.apiSecretEncrypted),
    accessToken: decrypt(brokerAccount.accessTokenEncrypted),
  };

  const adapter = BrokerFactory.getAdapter(brokerAccount.brokerCode, credentials);

  // Send order to broker
  const brokerResponse = await adapter.placeOrder({
    symbol,
    exchange,
    side,
    type,
    quantity,
    price,
  });

  // Persist live order in database
  const liveOrder = await prisma.order.create({
    data: {
      deploymentId,
      userId,
      brokerAccountId,
      brokerOrderId: brokerResponse.brokerOrderId,
      symbol,
      exchange,
      side,
      type,
      quantity,
      price,
      status: brokerResponse.success ? 'OPEN' : 'REJECTED',
      mode: 'LIVE',
      idempotencyKey,
      rejectionReason: brokerResponse.success ? null : brokerResponse.message,
    },
  });

  return liveOrder;
};

/**
 * Get user orders
 */
const getUserOrders = async (userId, query = {}) => {
  const { deploymentId, status, page = 1, limit = 20 } = query;
  const where = { userId };
  if (deploymentId) where.deploymentId = deploymentId;
  if (status) where.status = status;

  const [orders, total] = await Promise.all([
    prisma.order.findMany({
      where,
      skip: (page - 1) * limit,
      take: limit,
      orderBy: { createdAt: 'desc' },
      include: {
        deployment: {
          select: { id: true, strategy: { select: { name: true } } },
        },
      },
    }),
    prisma.order.count({ where }),
  ]);

  return { orders, total, page, limit };
};

/**
 * Get user positions
 */
const getUserPositions = async (userId) => {
  return await prisma.position.findMany({
    where: { userId, status: 'OPEN' },
    orderBy: { createdAt: 'desc' },
    include: {
      deployment: {
        select: { id: true, mode: true, strategy: { select: { name: true } } },
      },
    },
  });
};

module.exports = {
  executeOrder,
  getUserOrders,
  getUserPositions,
};
